### PR TITLE
Added Codespell workflow

### PR DESCRIPTION
**Pull request by Mohitkumar6122**
Fixes for #140.
Added Codespell workflow to  automate the identification of common misspellings in text files.

### CODE REVIEW

**Comment by laike9m** [comment]
Have you tried run it and see if it works?

**Comment by Mohitkumar6122** [comment]
@laike9m, what are your suggestions, if we can add ```typos``` or ```codespell``` works fine?

**Comment by laike9m** [comment]
Let's add both, no harm to do that and we'll see how it goes.

**Comment by Mohitkumar6122** [comment]
> Btw, you can request a review so I know. It's better than leaving a comment. Just a suggestion, not a big deal.

I know @laike9m, but Pull request authors can't request reviews unless they are either a repository owner or collaborator with write access to the repository.

**Comment by Mohitkumar6122** [comment]
> Does typos require us to put a `_typos.toml` at the root directory? I'm really against putting more files on the root directory. Is it possible to move the settings into `.github/workflows/typos.yml`? If we cannot, then I would say don't add it.

Surely @laike9m, I'll search for possible ways for this problem!

**Comment by laike9m** [comment]
ok, so that means "NO". Let's remove typos, then I'll LGTM. Thanks for looking into this!

**Pull request merged**
